version: '2'
services:
  gateway-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      POINTS_URL: '192.168.99.101'
      POINTS_PORT: '3301'
      POINTS_ENTRY: 'points/'
      FAVORITES_URL: '192.168.99.101'
      FAVORITES_PORT: '3302'
      FAVORITES_ENTRY: 'favorites/'
      COMMENTS_URL: '192.168.99.101'
      COMMENTS_PORT: '3303'
      COMMENTS_ENTRY: 'comments/'
      USERS_URL: '192.168.99.101'
      USERS_PORT: '4004'
      USERS_ENTRY: 'users/'
      CAMPAIGNS_URL: '192.168.99.101'
      CAMPAIGNS_PORT: '3305'
      CAMPAIGNS_ENTRY: 'campaigns/'
      STATS_URL: '192.168.99.101'
      STATS_PORT: '3306'
      STATS_ENTRY: 'stats/'

    ports:
      - '5000:5000'
